services:
  firefox:
    image: linuxserver/firefox
    container_name: firefox
    restart: unless-stopped
    environment:
      - LC_ALL=pt_BR.UTF-8
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    ports:
      - 3000:3000
      - 3003:3003
    shm_size: '2gb'
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./firefox_scripts:/custom-cont-init.d:ro
      - ./firefox_services:/custom-services.d:ro
      - /tmp/X11-unix:/tmp/.X11-unix
